# Use an official Python runtime as a parent image
### for DASK :

#FROM python:3.9

#ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app"


## Set the working directory in the container
#WORKDIR /usr/src/app

## Copy the current directory contents into the container at /usr/src/app
#COPY . /usr/src/app

## Install Python packages
##RUN pip install numpy pandas matplotlib scipy sklearn dask distributed
## Install Python packages
#RUN pip install numpy pandas matplotlib scipy scikit-learn dask distributed


## Make port 8786 available to the world outside this container
#EXPOSE 8786
#EXPOSE 8787

## Run your script when the container launches
#CMD ["python", "NY_Model_Dask.py"]

##################################

# Use an official Python runtime as a parent image

### for SPARK:

#FROM python:3.9

## Install Java (Spark dependency)
#RUN apt-get update -y && \
#    apt-get install -y openjdk-11-jdk

## Set environment variables for Java and Spark
#ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
#ENV SPARK_HOME /usr/local/spark
#ENV PATH $PATH:$JAVA_HOME/bin:$SPARK_HOME/bin:$SPARK_HOME/sbin
#ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app"

## Download and install Spark
#RUN apt-get update && \
#    apt-get install -y wget && \
#    wget https://downloads.apache.org/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz && \
#    tar xvf spark-3.2.0-bin-hadoop3.2.tgz && \
#    mv spark-3.2.0-bin-hadoop3.2 /usr/local/spark && \
#    rm spark-3.2.0-bin-hadoop3.2.tgz

## Install Python packages
#RUN pip install numpy pandas matplotlib scipy scikit-learn pyspark

## Set the working directory in the container
#WORKDIR /usr/src/app

## Copy the current directory contents into the container at /usr/src/app
#COPY . /usr/src/app

## Make port 8786 and 8787 available to the world outside this container
## Also expose Spark UI port 4040
#EXPOSE 8786 8787 4040

## Run your script when the container launches
#CMD ["python", "NY_Model_Dask.py"]


####################

# for Ray:

# Use an official Python runtime as a parent image
FROM python:3.9

# Set environment variables
ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app"

ENV RAY_ENABLE_WINDOWS_OR_OSX_CLUSTER=1


# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Install Python packages
RUN pip install numpy pandas matplotlib scipy scikit-learn ray
RUN pip install 'ray[default]'
RUN apt-get update && apt-get install -y netcat-openbsd

# Make port 6379 available for Ray dashboard
EXPOSE 6379

## Run your script when the container launches
#CMD ["python", "NY_Model_Ray.py"]

# open a command prompt when container launches
CMD ["/bin/bash"]


