name: Deploy to Azure Web App

on:
  push:
    branches:
      - my-new-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

        
    - name: Verify backend directory and log its contents
      run: |
        if [ ! -d "./backend" ]; then
          echo "Backend directory does not exist."
          exit 1
        fi
        echo "Backend directory exists."
        ls -al ./backend

    - name: Create and activate virtual environment, install dependencies, and run tests
      working-directory: ./backend
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list
        ls -al
        echo "print('Hello from test script')" > test_script.py
        python test_script.py
        echo "print('Testing main.py execution')" > test_main.py
        echo "import main" >> test_main.py
        python test_main.py

    - name: Verify backend installed packages
      working-directory: ./backend
      run: |
        pip list
    
    - name: List files in backend directory
      working-directory: ./backend
      run: ls -al

    - name: Run a test Python script
      working-directory: ./backend
      run: |
        echo "print('Hello from test script')" > test_script.py
        python test_script.py

    - name: Verify backend installed packages
      working-directory: ./backend
      run: pip list

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Build frontend
      working-directory: ./frontend
      run: |
        npm run build

    - name: Run tests (if any)
      working-directory: ./backend
      run: |
        # Add your test script here, for example:
        # python -m unittest discover -s tests
        echo "Run tests"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: AskYorkville
        slot-name: test08052024
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
