name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - test-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or any version your app requires

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn

    - name: 'Upload artifact for deployment job'
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YourAppName'  # Replace with your Azure Web App name
        slot-name: 'production'  # or the name of your slot, if using a deployment slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
