name: Build and Deploy Combined App to Azure Web App

on:
  push:
    branches:
      - DockerAppSimple  # Only trigger on the DockerApp branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          #creds: '{"clientId":"d628f8fa-ac3e-4a7a-a7e8-bc386cb884d4","clientSecret":${{ secrets.AZURE_CREDENTIALS }},"subscriptionId":"5cb9d786-4789-4403-9c63-44493daf4bbd","tenantId":"8d7d67b6-2968-4815-9c54-4906afe68b5c"}'
          #creds: '{"clientId":"d628f8fa-ac3e-4a7a-a7e8-bc386cb884d4","clientSecret":"AJf8Q~P0vKPxFBv6FqBjT6dLwojUnAkcjLNasbwg","subscriptionId":"5cb9d786-4789-4403-9c63-44493daf4bbd","tenantId":"8d7d67b6-2968-4815-9c54-4906afe68b5c"}'
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Set up Docker Compose'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to Azure Container Registry'
        run: |
          echo "GhcOYAY8Upxcv2m1YJMOki8vaA7WdF01Sgh+EWj1hY+ACRDDub0R" | docker login yorkvilleregistry.azurecr.io -u yorkvilleregistry --password-stdin

      - name: 'Define IMAGE_TAG'
        run: echo "IMAGE_TAG=charlie-combined:$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

       
      - name: 'Configure Azure App Service Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'YorkvilleCharlie'
          app-settings-json: |
            [
              {
                "name": "OPENAI_API_KEY",
                "value": "${{ secrets.OPENAI_API_KEY }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_STORAGE_ACCOUNT_KEY",
                "value": "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}",
                "slotSetting": false
              }
            ]
          startup-command: 'uvicorn main:app --host 0.0.0.0 --port 8000'

      
      
      - name: 'Build and push Docker image'
        run: |
          docker buildx build --platform linux/amd64 --no-cache -t yorkvilleregistry.azurecr.io/${{ env.IMAGE_TAG }} -f Dockerfile . --load
          docker push yorkvilleregistry.azurecr.io/${{ env.IMAGE_TAG }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Charlie2'
          images: 'yorkvilleregistry.azurecr.io/${{ env.IMAGE_TAG }}'
