name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - test-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or any version your app requires

    - name: Create and activate virtual environment, install dependencies, and run tests
      working-directory: ./backend
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      run: |
        python -m venv venv
        . venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list
        ls -al
        echo "print('Hello from test script')" > test_script.py
        python test_script.py
        echo "print('Testing main.py execution')" > test_main.py
        echo "import main" >> test_main.py
        python test_main.py

    - name: 'Upload artifact for deployment job'
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AskYorkville'  # Replace with your Azure Web App name
        slot-name: 'production'  # or the name of your slot, if using a deployment slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
