name: Deploy to Azure Web App

on:
  push:
    branches:
      - my-new-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify backend installed packages
      working-directory: ./backend
      run: |
        pip list

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Build frontend
      working-directory: ./frontend
      run: |
        npm run build

    - name: Run tests (if any)
      working-directory: ./backend
      run: |
        # Add your test script here, for example:
        # python -m unittest discover -s tests
        echo "Run tests"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: AskYorkville
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
