# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Charlie2

on:
  push:
    branches:
      - DockerAppSimple
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://yorkvilleregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_edd123e0f7c4460f8d32762880809e42 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cd60f877972549ac8bee8a6f21933cba }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yorkvilleregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_edd123e0f7c4460f8d32762880809e42 }}/charlie-combined:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Charlie2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7a883464fdd442d2b47d8afa40b8e606 }}
        images: 'yorkvilleregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_edd123e0f7c4460f8d32762880809e42 }}/charlie-combined:${{ github.sha }}'